apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels: 
    app: mongo
spec:
  containers:
    - name: mongo
      image: mongo
      ports: 
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            secretKeyRef: 
              name: mongo-creds
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: mongo-creds
              key: MONGO_INITDB_ROOT_PASSWORD
