apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels: 
    app: mongo
spec:
  containers:
    - name: mongo
      image: mongo
      ports: 
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
